version: "3.8"
services:

  neo4j:
    image: neo4j:5.16-community-bullseye
    container_name: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/

volumes:
  neo4j_data: